### ISSUE TITLE
How set password in excel file

### ISSUE THREAD

**Issue by githubshubham90** [pruiz/EPPlus#10]
Hi,

I am using EPPlus in ASP.Net MVC Core 2.0 and trying to create an excel file with password protected. I am using below code:
```
excelPackage.Encryption.Password = "sddd";
excelPackage.SaveAs(new FileInfo("<filepath>"));
```
It gives me error as below and unable to save file.
```
{System.TypeLoadException: Could not load type 'System.Security.Cryptography.RIPEMD160Managed' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at OfficeOpenXml.Encryption.EncryptedPackageHandler.GetHashProvider(EncryptionKeyEncryptor encr)
   at OfficeOpenXml.Encryption.EncryptedPackageHandler.EncryptPackageAgile(Byte[] package, ExcelEncryption encryption)
   at OfficeOpenXml.ExcelPackage.Save()}
```
Please help me.

**Comment by pruiz** [comment]
I am sorry, but this is not EEPlus' oficial repository, but my own fork with misc changes.
