### ISSUE TITLE
Unexpected size (0x0004) for NTFS times extra field at position 0x0000000000000B14

### ISSUE THREAD

**Issue by youlin99** [pruiz/EPPlus#8]
Bug reproduce steps:
1. open any folder on windows, right click menu, [NEW] -> [Microsoft Excel Worksheet], rename it to anything, let's say xxx.xlsx
2. open this xxx.xlsx with EPPlus in c# code, like
```
try
{
   string file = @".........\ppp.xlsx";
                FileInfo newFile = new FileInfo(file);
                using (ExcelPackage xlPackage = new ExcelPackage(newFile))
                {.....}
}
catch(Excpetion ex)
{}
```
3. we will get exception 
"Unexpected size (0x0004) for NTFS times extra field at position 0x0000000000000B14"
detailed stack trace is:
   at OfficeOpenXml.Packaging.Ionic.Zip.ZipEntry.ProcessExtraFieldWindowsTimes(Byte[] buffer, Int32 j, Int16 dataSize, Int64 posn)
   at OfficeOpenXml.Packaging.Ionic.Zip.ZipEntry.ProcessExtraField(Stream s, Int16 extraFieldLength)
   at OfficeOpenXml.Packaging.Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at OfficeOpenXml.Packaging.Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipInputStream.GetNextEntry()
   at OfficeOpenXml.Packaging.ZipPackage..ctor(Stream stream)
   at OfficeOpenXml.ExcelPackage.ConstructNewFile(String password)
   at OfficeOpenXml.ExcelPackage..ctor(FileInfo newFile)
   at SimpleWinFormTest.Form1.button1_Click(Object sender, EventArgs e) in .......\Form1.cs:line 116
4. that's all
![bug](https://user-images.githubusercontent.com/22915084/29399947-d411f028-835d-11e7-98ed-a7ff97fe0cfa.png)

**Comment by pruiz** [comment]
Hi,

This is not the official EEPlus package repository. Just a mere fork for my own needs.
